version: '2.0'

services:
  ci3-web:
    build:
      context: ./docker/images/php80-apache-pcntl
    volumes:
      - ./:/var/www/html
      - ./docker/images/php80-apache-pcntl/php.ini:/usr/local/etc/php/php.ini
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_enable=1 remote_autostart=1
    networks:
      - codeigniter3-network
      - traefik-network
    depends_on:
      - mysql-db
    labels:
      - "traefik.http.routers.ci3-tpl.rule=Host(`ci3-tpl.local`)"
      - "traefik.docker.network=traefik-network"

  mysql-db:
    image: mysql:5.7
    networks:
      - codeigniter3-network
    volumes:
      - ./docker/volumes/mysql/:/var/lib/mysql
    command: mysqld --sql_mode="NO_ENGINE_SUBSTITUTION" --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES UTF8MB4;' --innodb-flush-log-at-trx-commit=0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "my2276"

networks:
  codeigniter3-network:
    driver: bridge
  traefik-network:
    external: true
